### ISSUE TITLE
go get -v github.com/nleeper/goment error

### ISSUE THREAD

**Issue by abdullateef97** [nleeper/goment#27]
Tried doing `go get -v github.com/nleeper/goment`
### Expected Behaviour
Install successfully
### Error
`../../pkg/mod/github.com/nleeper/goment@v1.0.8/goment.go:7:2: module github.com/nleeper/goment@latest found (v1.0.8), but does not contain package github.com/nleeper/goment/internal/locales
`

**Comment by nleeper** [comment]
Thanks, will take a look.

**Comment by nleeper** [comment]
I've pushed up a new version 1.0.10. Seems like a bad tag got created for v1.0.8, so that's where the error came from. New to go modules, so been a bit of a learning curve. Looking to remove the modules under the internal folder in a future version, they've been a lot more pain than I anticipated. Let me know if this new version fixes things.

**Comment by abdullateef97** [comment]
yo @nleeper thanks, it fixed it. I would be closing the issue now. Thanks
